.github/workflows/ci.yml
.github/workflows/update-versions.yaml

Resolves https://github.com/calyptia/core-product-release/actions/runs/4045737182/jobs/6957624844
Signed-off-by: Patrick Stephens <pat@calyptia.com>

workflows: fix incorrect tag

---

.github/workflows/update-versions.yaml

Signed-off-by: Patrick Stephens <pat@calyptia.com>

workflows: fix jq usage

---

.github/workflows/update-versions.yaml

No need currently as not being used.

workflows: reduce to calling once a day

---

.github/workflows/get-latest-tag.yaml
.github/workflows/update-versions.yaml
component-config.json

Add other component versions that are missing.

Add Frontend, LUA Sandbox and Core Operator versions

---

.github/workflows/update-product-version.yaml
README.md

Check product exists
Convert to numeric value

workflows: add basic docs and sanity checks

---

README.md

docs: update DAG

---

.github/workflows/update-product-version.yaml

Version was missing as not exported properly.
Resolves failure here: https://github.com/calyptia/core-fluent-bit/actions/runs/6535924311/job/17746783038
Part of https://app.asana.com/0/1204881426070801/1205755377036922/f

workflows: fix missing version

---

README.md

Provide tagging details and some extra Core Docs info.

docs: Update for tagging and docs

---

README.md
component-config.json

Added the core-sidecar-ingest-check component.

core_sidecar_ingest_check: added

---

.github/workflows/release.yaml

Resolve issue with missing capture groups from #83

workflows: fix issue with bash rematch

---

.github/workflows/release.yaml

Fixes two issues during release creation: https://github.com/calyptia/core-product-release/actions/runs/6933293070
- File upload
- Docs missing file

workflows: fix release niggles

---

.github/workflows/release.yaml

SBOMs overflow the release creation.

workflows: fix SBOM upload overflow

---

.github/workflows/release.yaml

Resolves various failures in release: https://github.com/calyptia/core-product-release/actions/runs/6982146468

workflows: fix release failures

---

.github/workflows/call-integration-tests.yaml

Ensure we provide the CLI image variable and GITHUB_TOKEN too.

workflows: add CLI image variable

---

.github/workflows/run-integration-tests.yaml

Fix linting failures from typos in the new workflow.

workflows: add dispatchable tests

---

.github/workflows/call-fleet-integration-tests.yaml

Merging changes to default branch to support LTS.

workflows: windows Fleet fixes

---

.github/workflows/ci.yml

removes branch ref added for testing

vcluster: fix branch ref

---

.github/workflows/call-integration-tests.yaml

removes ref from get_versions step

fix: remove ref from get_versions step

---

.github/workflows/create-self-hosted-stack.yaml

Requires https://github.com/calyptia/api/pull/261

workflows: ignore expected failures in API tests

---

.github/workflows/call-integration-tests.yaml

Add useful job information about resource usage of the VM to confirm sizing is correct for Actuated.
https://gist.github.com/alexellis/1f33e581c75e11e161fe613c46180771
See: https://github.com/calyptia/core-product-release/actions/runs/7276547935/job/19826655550?pr=146#step:58:1
```
2023-12-20T14:46:34.7003231Z Total RAM: 15.26GB
2023-12-20T14:46:34.7003495Z Total vCPU: 4
2023-12-20T14:46:34.7003634Z 
2023-12-20T14:46:34.7003739Z Load averages:
2023-12-20T14:46:34.7003973Z Max 1 min: 1.66 (41.50%)
2023-12-20T14:46:34.7004227Z Max 5 min: 0.49 (12.25%)
2023-12-20T14:46:34.7004488Z Max 15 min: 0.27 (6.75%)
2023-12-20T14:46:34.7004639Z 
2023-12-20T14:46:34.7004734Z RAM usage (400 samples):
2023-12-20T14:46:34.7004979Z Max RAM usage: 1.879GB
2023-12-20T14:46:34.7005140Z …
```

workflows: add metering support for Actuated jobs

---

.github/workflows/call-integration-tests.yaml
.github/workflows/run-integration-tests.yaml
scripts/run-integration-tests.sh

Fix issue with vCluster usage during tests not having GKE auth plugin.

scripts: ensure we install GKE auth plugin

---

.github/workflows/call-fleet-integration-tests.yaml
.github/workflows/call-integration-tests.yaml
.github/workflows/ci.yml
.github/workflows/get-versions.yaml
.github/workflows/release.yaml
.github/workflows/update-product-version.yaml

migration: update

---

.github/workflows/update-versions.yaml

Resolves https://github.com/chronosphereio/calyptia-core-product-release/actions/runs/8121121255/job/22199122577 failures.

workflows: remove legacy Core references

---

.github/workflows/get-latest-tag.yaml
.github/workflows/update-versions.yaml

Resolve failures like this: https://github.com/chronosphereio/calyptia-core-product-release/actions/runs/8136888185

workflows: fix repo names after migration

---

.github/workflows/update-versions.yaml

Workflow tweak to resolve failures like https://github.com/chronosphereio/calyptia-core-product-release/actions/runs/8152275103/job/22281489892

[sc-84903]: fix typo in update versions workflow

---

.github/workflows/update-versions.yaml

Trivial typo fix of extra quotes.

workflows: fix incorrect quotes usage

---

CODEOWNERS

config: add codeowners

---

.github/workflows/update-versions.yaml

Changes from #182 seem to have not quite fixed things.

[sc-91303]: fixup CI

---

.github/workflows/cron-vuln-scan.yaml
.github/workflows/get-versions.yaml

Some post-merge fixes to resolve problems

Fix up CVE scan workflow

---

.github/workflows/cron-vuln-scan.yaml

Switch to using dedicated Slack automation.

Use Slack workflow for CVEs

---

.github/workflows/cron-vuln-scan.yaml

Fix up CVE workflow to correctly create JSON payload for Slack.
See https://chronosphereio.slack.com/archives/C06DW9RAT1B/p1717694991313739

workflows: update to fix up JSON

---

scripts/run-integration-tests.sh

Same change from here https://github.com/chronosphereio/calyptia-cloud-e2e/pull/186

fix: extract calyptia cli from docker
